In [116]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [151]:
import numpy as np
import pandas as pd
import json
from bivariate_correlation import IncrementalBivariateCorrelation
from time import clock

In [152]:
def callback(relevancies, redundancies, feature_slices):
    print('relevancies: \n', relevancies, '\n')
    print('redundancies: \n', redundancies.redundancy, '\n')
    print('weights: \n', redundancies.weight, '\n')
    for feature, slices in feature_slices.items():
        print('featureset:', feature)
        current_slices = [{'feature' : name, 'slices' : df.transpose().to_dict()} 
                          for name, df in pd.concat([slices.categorical, slices.continuous]).iteritems()]
        print(current_slices)
    print('\n\n\n')

In [186]:
dataset = '../data/mysynthetic.csv'
data = pd.read_csv(dataset)
correlation = IncrementalBivariateCorrelation(data, '0', iterations = 10, alpha = 0.1, drop_discrete = True)

In [187]:
relevancies, redundancies, feature_slices = correlation.calculate_correlation(limit = 5, callback = callback)

relevancies: 
   feature     score
0       1  0.427992
1       2  0.276324
2       3  0.106202
3       4  0.000185
4       5  0.000136
5       6  0.000228
6       7  0.000105
7       8  0.000108
8       9  0.000153 

redundancies: 
           1         2         3         4         5         6         7  \
1  0.000000  0.030668  0.000000  0.030668  0.010223  0.000000  0.010223   
2  0.030668  0.000000  0.000060  0.000000  0.000060  0.000034  0.000060   
3  0.000000  0.000060  0.000000  0.000000  0.000000  0.000000  0.000000   
4  0.030668  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
5  0.010223  0.000060  0.000000  0.000000  0.000000  0.000000  0.000000   
6  0.000000  0.000034  0.000000  0.000000  0.000000  0.000000  0.000000   
7  0.010223  0.000060  0.000000  0.000000  0.000000  0.000000  0.000000   
8  0.000000  0.000000  0.000025  0.000000  0.000000  0.000000  0.000000   
9  0.010223  0.000023  0.000020  0.000000  0.000000  0.000000  0.000000   

          8     

In [176]:
print(correlation.subspace_slices['["9"]'].continuous['9'])

        end     start
0  2.377785  1.877448
2  2.056478  1.554599
5  0.410467 -0.095292
6  3.245502  2.753723
7  3.522082  3.031380


In [115]:
test_df = pd.DataFrame({'0' : [0, 0, 1, 1, 1], '1' : [0, 1, 1, 1, 0], '2' : [0, 1, 1, 1, 1]})
print(test_df)

data_array = np.array([np.array(test_df).tolist()] * len(test_df))
size_array = np.apply_along_axis(lambda x: (x*1).sum(), 2, data_array)

min_size = np.minimum(size_array, size_array.T)
overlap = np.apply_along_axis(lambda x: (x*1).sum(), 2, np.logical_and(data_array, data_array.transpose(1, 0, 2)))

min_size[min_size == 0] = 1
print(min_size)
print(overlap)
print(overlap/min_size)

print(overlap[0, 0] == 0, overlap[2, 3] == 3, overlap[1, 4] == 1)

   0  1  2
0  0  0  0
1  0  1  1
2  1  1  1
3  1  1  1
4  1  0  1
[[1 1 1 1 1]
 [1 2 2 2 2]
 [1 2 3 3 2]
 [1 2 3 3 2]
 [1 2 2 2 2]]
[[0 0 0 0 0]
 [0 2 2 2 1]
 [0 2 3 3 2]
 [0 2 3 3 2]
 [0 1 2 2 2]]
[[ 0.   0.   0.   0.   0. ]
 [ 0.   1.   1.   1.   0.5]
 [ 0.   1.   1.   1.   1. ]
 [ 0.   1.   1.   1.   1. ]
 [ 0.   0.5  1.   1.   1. ]]
True True True


In [ ]:
test_list = [2, 3, 4, 5]
for current in test_list:
    